// ============================================================
// Sky Fighter - 게임 설정 및 상수
// ============================================================

const GAME_WIDTH = window.innerWidth;
const GAME_HEIGHT = window.innerHeight;

// 비행기 스탯 정의
const PLANE_DATA = {
    falcon: {
        name: 'FALCON',
        desc: '균형잡힌 전투기',
        speed: 450,
        fireRate: 160,
        lives: 3,
        bulletSpeed: -550,
        bulletCount: 2,
        color: { body: 0x4466aa, highlight: 0x7799cc, cockpit: 0x66ddff, wing: 0x3355aa, engine: 0x00ff66 },
    },
    thunder: {
        name: 'THUNDER',
        desc: '강력한 화력의 폭격기',
        speed: 350,
        fireRate: 220,
        lives: 5,
        bulletSpeed: -450,
        bulletCount: 3,
        color: { body: 0x886633, highlight: 0xaa8844, cockpit: 0xffcc44, wing: 0x775522, engine: 0xff8800 },
    },
    phantom: {
        name: 'PHANTOM',
        desc: '빠른 경량 전투기',
        speed: 600,
        fireRate: 100,
        lives: 2,
        bulletSpeed: -700,
        bulletCount: 1,
        color: { body: 0x664488, highlight: 0x8866aa, cockpit: 0xcc66ff, wing: 0x553377, engine: 0xcc44ff },
    },
    viper: {
        name: 'VIPER',
        desc: '독사처럼 빠른 요격기',
        speed: 550,
        fireRate: 130,
        lives: 2,
        bulletSpeed: -650,
        bulletCount: 2,
        color: { body: 0x228844, highlight: 0x44aa66, cockpit: 0x44ff88, wing: 0x116633, engine: 0x00ff44 },
    },
    raptor: {
        name: 'RAPTOR',
        desc: '최신예 스텔스 전투기',
        speed: 480,
        fireRate: 140,
        lives: 4,
        bulletSpeed: -580,
        bulletCount: 3,
        color: { body: 0x555555, highlight: 0x888888, cockpit: 0xaaddff, wing: 0x444444, engine: 0x44aaff },
    },
};

// 스테이지 설정
const STAGE_CONFIG = [
    { // Stage 1 - 입문
        enemySpawnDelay: 1600,
        missileDelay: 2200,
        enemySpeed: [140, 220],
        enemyHP: 1,
        missileSpeed: [220, 320],
        missileChance: 0.4,
        diagonalChance: 0.2,
        aimedChance: 0.1,
        killsToAdvance: 12,
        bossHP: 30,
        label: 'STAGE 1',
        subtitle: '정찰 구역',
    },
    { // Stage 2 - 전초전
        enemySpawnDelay: 1200,
        missileDelay: 1800,
        enemySpeed: [170, 260],
        enemyHP: 2,
        missileSpeed: [250, 370],
        missileChance: 0.5,
        diagonalChance: 0.35,
        aimedChance: 0.2,
        killsToAdvance: 15,
        bossHP: 40,
        label: 'STAGE 2',
        subtitle: '적 전초기지',
    },
    { // Stage 3 - 격전
        enemySpawnDelay: 950,
        missileDelay: 1400,
        enemySpeed: [200, 300],
        enemyHP: 2,
        missileSpeed: [280, 420],
        missileChance: 0.6,
        diagonalChance: 0.45,
        aimedChance: 0.3,
        killsToAdvance: 18,
        bossHP: 50,
        label: 'STAGE 3',
        subtitle: '치열한 교전',
    },
    { // Stage 4 - 돌파
        enemySpawnDelay: 750,
        missileDelay: 1100,
        enemySpeed: [230, 340],
        enemyHP: 3,
        missileSpeed: [320, 460],
        missileChance: 0.7,
        diagonalChance: 0.5,
        aimedChance: 0.4,
        killsToAdvance: 20,
        bossHP: 60,
        label: 'STAGE 4',
        subtitle: '적 요새 돌파',
    },
    { // Stage 5 - 최종결전
        enemySpawnDelay: 600,
        missileDelay: 900,
        enemySpeed: [260, 380],
        enemyHP: 3,
        missileSpeed: [350, 500],
        missileChance: 0.8,
        diagonalChance: 0.6,
        aimedChance: 0.5,
        killsToAdvance: 25,
        bossHP: 80,
        label: 'STAGE 5',
        subtitle: '최종 결전',
    },
];
